### ISSUE TITLE
GIS info request

### ISSUE THREAD

**Issue by baymodeling** [rustychris/sfbay_potw#1]
Great data! Coordinates of discharge points and full names/descriptions of dischargers are requested.

**Comment by rustychris** [comment]
Added a shapefile under sources/ with long names, short names (which match the flow data), lat/lon.  I'm labeling this issue and enhancement, since there is still some work needed to pull these shapefile data into the netcdf output, and maybe generate a csv version of the shapefile data, too.  But at least the information is present now.

**Comment by rustychris** [comment]
The geographic information should be carried into the netcdf properly now.
